### PR TITLE
[ERROR] Update ArrayObject.php in 2.7.7

### PR DESCRIPTION
**Pull request by Blaztix**
Provide a narrative description of what you are trying to accomplish:

- Are you fixing a bug?
  - Detail how the bug is invoked currently.

  Just install zendframework and get error with this.

- Is this related to quality assurance?
I using a old php program this throw an error, and not is fixed in 2.7.7

### CODE REVIEW

**Comment by webimpress** [comment]
@Blaztix Unfortunately zend-stdlib v2 is no longer supported. Please see:
https://framework.zend.com/long-term-support for details.

Here you can see the hotfix to version 3: https://github.com/zendframework/zend-stdlib/pull/91

**Comment by Blaztix** [comment]
This is ridiculous, I'm not going to update a complete platform because a pull request can not be accepted.... 

* Add and restriction for PHP version
or
* Just add a literal ` 2` or replace with `break` and release a 2.7.8 or hotfix

I am an simple user running `composer install` and gets errors.... unacceptable

**Comment by Ocramius** [comment]
That's what you will get with any older release of a library. Upgrading is
the correct resolution path: otherwise, run an older PHP version.

**Comment by YetiCGN** [comment]
Oh, I see that this has already been addressed. I just came across the same problem and will continue to use my fork of zend-stdlib 2.7.7 with the fix applied.

@Blaztix You can do the same, just add the forked repository in your `composer.json` and add or change the following line:
```
"zendframework/zend-stdlib": "dev-release-2.7 as 2.7.8",
```

**Comment by YetiCGN** [comment]
> That's what you will get with any older release of a library. Upgrading is the correct resolution path: otherwise, run an older PHP version.

While I understand the rationale behind that and why making an exception for this one-line fix would call upon all sorts of "small fixes" for an outdated version, what people will really do is 
a) silence the warning 
or
b) use a fork (like I do) with the patch applied.

Actually this is more a problem of Apigility claiming compatibility with `php: ^5.6 || ^7.0` but not really being tested on 7.3 and 7.4. So people are finding out late in the testing process (like I did) when they likely already have switched to PHP 7.3 what with the accelerated release cycle of PHP. And then it's just a nuisance that can be silenced pretty easily. So no. I will not invest countless days into upgrading this legacy project to a newer version of Zend Framework.

Symfony forever!!! 😛

**Pull request closed without merging**
