### PR TITLE
fixed issue #8 with count increment on insert

### PR DESCRIPTION
**Pull request by dankobiaka**
Added additional check to only increment count if item doesn't already exist.

### CODE REVIEW

**Comment by Ocramius** [comment]
@dankobiaka this requires a test case :-)

**Comment by dankobiaka** [comment]
complete

**Comment by Maks3w** [comment]
@dankobiaka The PR conflicts with master. Could you please rebase your branch?

**Comment by dankobiaka** [comment]
is that okay now?

**Comment by weierophinney** [comment]
I've tagged zend-stdlib 2.4.4, and will be back-porting this to an LTS release of ZF2 today.

**Comment by Maks3w** [comment]
@weierophinney 2.5 should be released too

**Comment by weierophinney** [comment]
@Maks3w after I get the LTS release done, that's the plan.

**Comment by Maks3w** [comment]
Allow this fix to undo https://github.com/zendframework/zf2/pull/7446?

**Comment by weierophinney** [comment]
@Maks3w No; they're separate issues. This one has to do with the count, while the other has to do with removal of items during iteration. They're not related.

**Pull request closed without merging**
