### PR TITLE
Denglish

### PR DESCRIPTION
**Pull request by ThaDafinser**
change $datum to $value

### CODE REVIEW

**Comment by Ocramius** [comment]
What do you have against denglish? :-(

**Comment by ThaDafinser** [comment]
Personally nothing :wink:

**Comment by weierophinney** [comment]
This is a completely unnecessary change. The verbiage used is directly from what the SPL uses, and is a valid English word.

**Comment by Ocramius** [comment]
I was actually going to merge this :-\

**Comment by weierophinney** [comment]
I'd rather we focus on changes that have an impact: fixing bugs, adding
useful features. I don't see the point of changes like these; in time,
somebody else will send a new PR changing it back, or to different
verbiage, for no reason other than personal preference. The simplest path
is to leave it as is.

**Comment by Martin-P** [comment]
Denglish? The word "datum" is not used in Dutch as a plural for data. We always use the word "data" and don't have a singular word for it. You could call it Dutch frugality :smile: The word "datum" is always used as a translation for the English word "date" (as in day/month/year).

**Comment by Ocramius** [comment]
@Martin-P "Denglish" refers to "Deutsch-English", not "Dutch-English": Dutch is already Denglish to some degree :P

**Comment by Martin-P** [comment]
Lol, I get lots of articles about Dutch-English when searching for Denglish. Must be personalised search results based on my location. Dutch is almost English nowadays :stuck_out_tongue_winking_eye:

**Pull request closed without merging**
