### PR TITLE
Deprecate hydrator classes

### PR DESCRIPTION
**Pull request by weierophinney**
As [zend-hydrator](https://github.com/zendframework/zend-hydrator) has now been created, we can deprecate the various Hydrator classes.

The following is a checklist for what needs to happen:

- [x] Add a dependency on `zendframework/zend-hydrator`
- [x] Alter existing classes to extend their `zend-hydrator` equivalents. In some cases, this may require either decoration (some classes are marked final) or changes to `zend-hydrator` to accommodate extension.
- [x] Mark each class as `@deprecated`; we may also want to raise an `E_USER_DEPRECATED` error to flag to users they will need to update.
- [x] The HydratorPluginManager should *always* return the `zend-hydrator` instances, not the `zend-stdlib` equivalents.

Once complete, we will also need to update `zend-mvc` to start using `zend-hydrator` for the hydrator plugin manager integration.

### CODE REVIEW

**Comment by weierophinney** [comment]
Test coverage changes are to be expected with code removal. Honestly, looking at the report, it looks like it's a bunch of small coverage changes that, per file, are less than 1%, but which aggregate. I'm not concerned about it; tests are still passing.

**Comment by weierophinney** [comment]
@bakura10 and @ezimuel — please review. :sweat_smile:

**Comment by Maks3w** [comment]
Since v2.2 of phpunit coverage `@deprecate` has the same meaning of `@coverageignore` for that reason the column of "relevant lines" drops to 0 and a coverage of 100% is returned.

So because the project now has less "relevant lines" now each line has more weight in the global percent.

**Comment by ezimuel** [comment]
@weierophinney I reviewed the PR and it looks good to me.

**Comment by weierophinney** [comment]
I've tested Apigility against the current stable develop branch. 7752b57 fixes the only issue I encountered, which is that zf-hal was doing some type-hinting against `Zend\Stdlib\Extractor\ExtractionInterface`, and thus objects that implemented `Zend\Hydrator\HydratorInterface` were failing that contract. Changing `Zend\Stdlib\Hydrator\HydratorInterface` to extend `Zend\Stdlib\Extractor\ExtractionInterface` solved the issue, while still allowing such implementations to fulfill the zend-hydrator interfaces. (I mirrored this in 2e36707 to ensure any typehints against `Zend\Stdlib\Hydrator\HydrationInterface` when compared to objects implementing `HydratorInterface` will continue to work, too.)

At this point, the only thing that *will* require a change are any objects implementing `HydratorAwareInterface`, as they will need to update their signatures to use the zend-hydrator interfaces in the argument typehints.

**Comment by weierophinney** [comment]
I've updated the changelog to detail any necessary changes users may need. If using `HydratorAwareTrait`, no changes are required; for those implementing `HydratorAwareInterface` on their own, they will need to update the function signature of `setHydrator()`. Otherwise, everything is now working exactly as it was before, just with a different inheritance tree.

**Comment by weierophinney** [comment]
In IRC, @mwillbanks noted an issue in zend-db's `HydratingResultSet` when using a custom hydrator extending `AbstractHydrator`; `HydratingResultSet` typehints on `Zend\Stdlib\Hydrator\HydratorInterface`, and the custom hydrator was failing the type check.

I've now updated `AbstractHydrator` in zend-stdlib to *also* implement the local `HydratorInterface`, and added a test to demonstrate the problem (as well as the resolution).

**Comment by weierophinney** [comment]
To satisfy the LSP, I've updated all concrete classes to not only extend the relevant zend-hydrator counterparts, but to *also* implement the relevant local interfaces. This should obviate any issues with substitution in other classes.

One note at this time: users adopting zend-hydrator and implementing those interfaces will be in a strange situation where that code will not work on code targeting the stdlib interfaces. I'll note that in the release notes.

**Comment by weierophinney** [comment]
As a follow-up, I'll be updating the following repositories, using the following checklist, in the coming days to ensure they will work going forward, and use the zend-hydrator component for new minor versions:

- zend-modulemanager (`Feature\HydratorProviderInterface`)
- zend-form (`Factory`, `FieldsetInterface`, `Fieldset`, `Form`, `Annotation\FormAnnotationsListener`, `Annotation\AnnotationBuilder`, `Annotation\Hydrator`, `Annotation\ElementAnnotationsListener`)
- zend-mvc (`Service\HydratorManagerFactory`, `Service\ServiceListenerFactory`, `Service\ModuleManagerFactory`)
- zend-db (`ResultSet\HydratingResultSet`)
- zf-hal (`Plugin\Hal`)

Checklist:

- [ ] New maintenance release
  - [ ] Update composer.json to reference stdlib &lt; 2.7
  - [ ] Open PR and test on travis
  - [ ] Tag new release
- [ ] New minor release
  - [ ] Update develop branch to require zend-hydrator &gt;= 2.0
  - [ ] Update develop branch to require zend-stdlib &gt;= 2.7
  - [ ] Update code to reference zend-hydrator interfaces and/or concrete instances
  - [ ] Open PR and test on travis
  - [ ] Merge to master
  - [ ] Tag new minor release

**Pull request merged**
